version: '3.9'
services:
  app:
    build: ./infra/node
    ports:
      - '5500:5500'
    volumes:
      - ./:/src
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - db_data:/var/lib/posrgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
